#!/bin/sh
# SPDX-FileCopyrightText: Huawei Inc.
#
# SPDX-License-Identifier: Apache-2.0

set -e

# Bring up a OpenThread border router for the given configuration
ot-ctl thread stop
ot-ctl ifconfig down
ot-ctl dataset clear
ot-ctl dataset init new
ot-ctl dataset panid 0x1357
ot-ctl dataset extpanid 11112222deadbeef
ot-ctl dataset networkname OniroThread
ot-ctl dataset channel 26
#ot-ctl dataset masterkey 00112233445566778899aabbccddeeff
#ot-ctl dataset networkkey 00112233445566778899aabbccddeeff
# J01NME is the Commissioner Credential to be used in the Android app
# J01NU5 is the Joiner Credential, set in the node and QR code
ot-ctl dataset pskc $(pskc J01NME 11112222deadbeef OniroThread)
ot-ctl dataset commit active
#ot-ctl prefix add fd11:22::/64 pasor
ot-ctl ifconfig up
ot-ctl thread start
ot-ctl netdata register
#ot-ctl prefix add 2001::/64 paros
#ot-ctl dataset meshlocalprefix fdde:00be:ef00:aaaa::
