# SPDX-FileCopyrightText: Huawei Inc.
# SPDX-License-Identifier: MIT

# util-linux uses autogenerated non-literal format strings in its hexdump
# code. Those strings have been verified to be safe in 2.35.1.
#
# Removing -Werror=format-nonliteral here allows us to use
# -Werror=format-nonliteral globally in OPTIMIZE_FOR=security mode
# while keeping util-linux building.

TARGET_CFLAGS:remove = "-Werror=format-nonliteral"
