@startuml meta-ohos_system_context_diagram
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Context.puml

Person(dev, "Developer", "Anyone willing to build the OHOS based image")
System(meta_ohos, "meta-ohos", "meta-ohos umbrella bitbake layer")
System_Ext(yocto, "yocto-poky", "distro scaffolding: predefined meta-data, bitbake build system")

Rel(dev, yocto, "selects configuration, initiates the build, deploys image to the target")
Rel(yocto, meta_ohos, "incorporates")

@enduml