' SPDX-FileCopyrightText: Huawei Inc.
'
' SPDX-License-Identifier: CC-BY-4.0

@startuml smarthome-demo-arch
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

HIDE_STEREOTYPE()

title SmartHome demo architecture

Person(user, "User")
System(dashboard, "Dashboard", "Home Assistant software running on Avenger96 board, interfacing with the user via a touchscreen")

System_Ext(sensors_board, "Sensors board", "96Boards Nitrogen with the Sensors Mezzanine adapter and selected sensors connected")
System_Ext(smart_bulb, "Smart bulb/LED", "96Boards Nitrogen with the Sensors Mezzanine adapter and LED connected")

Rel(user, dashboard, "Uses")
Rel_Back(dashboard, sensors_board, "Sends sensors readings", "BLE")
Rel_Neighbor(dashboard, sensors_board, "Reads out sensors", "BLE")
Rel(dashboard, smart_bulb, "Controls", "BLE")
@enduml
